# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 01:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20160527_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationfield',
            name='created_on',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 30, 1, 29, 45, 157199, tzinfo=utc), verbose_name=b'Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authenticationfield',
            name='updated_on',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 30, 1, 29, 50, 309107, tzinfo=utc), verbose_name=b'Updated on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='created_on',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 30, 1, 29, 55, 365281, tzinfo=utc), verbose_name=b'Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_on',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 30, 1, 30, 4, 77016, tzinfo=utc), verbose_name=b'Updated on'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authenticationfield',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
