# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20160530_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationfield',
            name='help_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='authenticationfield',
            name='validator_regex',
            field=models.CharField(default='', max_length=1028),
        ),
    ]
