# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20160530_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationfield',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authenticationfield',
            name='title_fi',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
