# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20160603_1101'),
        ('organization', '0007_auto_20160606_1459'),
    ]

    operations = [
    ]
