# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20160610_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='authentification_fields_request',
            field=models.TextField(default=''),
        ),
    ]
