# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_auto_20160619_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='authentification_fields_request',
            field=models.TextField(blank=True, default='', help_text='Unique identifiers that organization needs and details of the identifiers.', null=True, verbose_name='Authentification fields request'),
        ),
    ]
