# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_auto_20160619_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='verified',
            field=models.BooleanField(default=True, help_text='Verified organizations are visible to all users', verbose_name='Verified'),
        ),
    ]
