# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_auto_20160619_2345'),
        ('organization', '0015_auto_20160619_1852'),
    ]

    operations = [
    ]
