# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDraft',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.Organization')),
                ('original_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_organizations', to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
            bases=('organization.organization',),
        ),
    ]
