# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name=b'Created on')),
                ('updated_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name=b'Updated on')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email_address', models.EmailField(blank=True, default='', help_text='Email address used by the organization to respond to user data requests', max_length=255, null=True, verbose_name='Email address')),
                ('address_line_one', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Address line 1')),
                ('address_line_two', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Address line 2')),
                ('postal_code', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Postal code')),
                ('country', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Country')),
                ('checked', models.BooleanField(default=False)),
                ('ignored', models.BooleanField(default=False)),
                ('updated', models.BooleanField(default=False)),
                ('authentication_fields', models.ManyToManyField(related_name='_organizationdraft_authentication_fields_+', to='organization.AuthenticationField')),
            ],
            options={
                'ordering': ('updated_on',),
                'verbose_name': 'organization edit draft',
                'verbose_name_plural': 'organization edit drafts',
            },
        ),
        migrations.RemoveField(
            model_name='organization',
            name='authentification_fields_request',
        ),
        migrations.AddField(
            model_name='organizationdraft',
            name='original_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_organizations', to='organization.Organization'),
        ),
    ]
