# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_organizationdraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='authentification_fields_request',
        ),
        migrations.AddField(
            model_name='organizationdraft',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationdraft',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationdraft',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
