# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_register'),
        ('organization', '0018_auto_20160703_1248'),
    ]

    operations = [
    ]
