# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 14:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name=b'Created on')),
                ('updated_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name=b'Updated on')),
                ('message', models.TextField()),
                ('rating', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
