# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_auto_20160706_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_on',)},
        ),
    ]
