# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_auto_20160707_1255'),
        ('organization', '0022_auto_20160708_1537'),
    ]

    operations = [
    ]
