# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0023_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(max_length=2000),
        ),
    ]
