# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0024_auto_20160711_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email_address',
            field=models.EmailField(blank=True, default='', help_text='Email address used by the organization for receiving data requests. Leave empty if the organization only accepts requests by post.', max_length=255, null=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='organizationdraft',
            name='email_address',
            field=models.EmailField(blank=True, default='', help_text='Email address used by the organization for receiving data requests. Leave empty if the organization only accepts requests by post.', max_length=255, null=True, verbose_name='Email address'),
        ),
    ]
