# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_auto_20160818_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registers', to='organization.Organization'),
        ),
    ]
