# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-24 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_auto_20160818_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationfield',
            name='order',
            field=models.IntegerField(default=777),
        ),
    ]
