# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0026_authenticationfield_order'),
        ('organization', '0026_auto_20160824_1409'),
    ]

    operations = [
    ]
