# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0027_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address_line_one',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address_line_two',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email_address',
            field=models.EmailField(blank=True, default='', help_text='Email address used by the organization for receiving data requests. Leave empty if the organization only accepts requests by post.', max_length=255, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='organizationdraft',
            name='address_line_one',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='organizationdraft',
            name='address_line_two',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='organizationdraft',
            name='country',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='organizationdraft',
            name='email_address',
            field=models.EmailField(blank=True, default='', help_text='Email address used by the organization for receiving data requests. Leave empty if the organization only accepts requests by post.', max_length=255, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='organizationdraft',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Postal code'),
        ),
    ]
