# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0028_auto_20160829_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='requested_amount',
            field=models.IntegerField(default=0),
        ),
    ]
