# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0029_organization_requested_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('-requested_amount', 'name')},
        ),
    ]
