# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0030_auto_20160830_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenticationfield',
            options={'ordering': ('-order',)},
        ),
    ]
