# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0031_auto_20160902_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenticationfield',
            options={'ordering': ('order',)},
        ),
    ]
