# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_auto_20160527_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('auth_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.AuthenticationField')),
            ],
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_requests', to='organization.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='authenticationcontent',
            name='data_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_contents', to='data_request.DataRequest'),
        ),
    ]
