# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 01:30
from __future__ import unicode_literals

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationcontent',
            name='created_on',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 30, 1, 29, 15, 925783, tzinfo=utc), verbose_name=b'Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authenticationcontent',
            name='updated_on',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 30, 1, 29, 24, 589713, tzinfo=utc), verbose_name=b'Updated on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datarequest',
            name='created_on',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 30, 1, 29, 32, 133524, tzinfo=utc), verbose_name=b'Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datarequest',
            name='updated_on',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 30, 1, 29, 39, 901294, tzinfo=utc), verbose_name=b'Updated on'),
            preserve_default=False,
        ),
    ]
