# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0002_auto_20160530_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequest',
            name='fields',
            field=models.ManyToManyField(to='data_request.AuthenticationContent'),
        ),
    ]
