# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0003_datarequest_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datarequest',
            name='fields',
        ),
    ]
