# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0005_pdfcontents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfcontents',
            name='content',
        ),
        migrations.AddField(
            model_name='pdfcontents',
            name='content1',
            field=models.TextField(blank=True, default='content eka'),
        ),
        migrations.AddField(
            model_name='pdfcontents',
            name='content2',
            field=models.TextField(blank=True, default='content toka'),
        ),
    ]
