# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0008_auto_20160603_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfcontents',
            options={'verbose_name_plural': 'pdf contents'},
        ),
    ]
