# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0012_auto_20160606_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name=b'Created on')),
                ('updated_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name=b'Updated on')),
                ('title', models.CharField(default='Default', max_length=255, unique=True)),
                ('header', models.TextField(blank=True, default='Dear recipient,')),
                ('content1', models.TextField(blank=True, default='content first')),
                ('content2', models.TextField(blank=True, default='content second')),
                ('footer', models.TextField(blank=True, default='Regards,')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='pdfcontents',
            name='content1',
            field=models.TextField(blank=True, default='content first'),
        ),
        migrations.AlterField(
            model_name='pdfcontents',
            name='content1_en',
            field=models.TextField(blank=True, default='content first', null=True),
        ),
        migrations.AlterField(
            model_name='pdfcontents',
            name='content1_fi',
            field=models.TextField(blank=True, default='content first', null=True),
        ),
        migrations.AlterField(
            model_name='pdfcontents',
            name='content2',
            field=models.TextField(blank=True, default='content second'),
        ),
        migrations.AlterField(
            model_name='pdfcontents',
            name='content2_en',
            field=models.TextField(blank=True, default='content second', null=True),
        ),
        migrations.AlterField(
            model_name='pdfcontents',
            name='content2_fi',
            field=models.TextField(blank=True, default='content second', null=True),
        ),
    ]
