# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0013_auto_20160627_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name=b'Created on')),
                ('updated_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name=b'Updated on')),
                ('title', models.CharField(default='', max_length=80)),
                ('ficontent', models.TextField(default='')),
                ('encontent', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
