# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0014_faq_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ_content',
            new_name='FaqContent',
        ),
    ]
