# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0015_auto_20160710_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcontent',
            name='ficontent_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='faqcontent',
            name='ficontent_fi',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='faqcontent',
            name='title_en',
            field=models.CharField(default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='faqcontent',
            name='title_fi',
            field=models.CharField(default='', max_length=80, null=True),
        ),
    ]
