# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0016_auto_20160710_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqcontent',
            old_name='encontent',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='faqcontent',
            old_name='ficontent_en',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='faqcontent',
            old_name='ficontent_fi',
            new_name='content_fi',
        ),
        migrations.RemoveField(
            model_name='faqcontent',
            name='ficontent',
        ),
    ]
