# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0018_auto_20160710_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcontent',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faqcontent',
            name='title_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faqcontent',
            name='title_fi',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
