# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0019_auto_20160710_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcontent',
            name='title',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='faqcontent',
            name='title_en',
            field=models.CharField(default='', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='faqcontent',
            name='title_fi',
            field=models.CharField(default='', max_length=75, null=True),
        ),
    ]
