# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0021_auto_20160710_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcontent',
            name='priority',
            field=models.IntegerField(default=777),
        ),
    ]
