# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0022_faqcontent_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name=b'Created on')),
                ('updated_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name=b'Updated on')),
                ('title', models.CharField(default='Default', max_length=255, unique=True)),
                ('header', models.TextField(blank=True, default='Dear recipient,')),
                ('header_en', models.TextField(blank=True, default='Dear recipient,', null=True)),
                ('header_fi', models.TextField(blank=True, default='Dear recipient,', null=True)),
                ('content1', models.TextField(blank=True, default='content first')),
                ('content1_en', models.TextField(blank=True, default='content first', null=True)),
                ('content1_fi', models.TextField(blank=True, default='content first', null=True)),
                ('content2', models.TextField(blank=True, default='content second')),
                ('content2_en', models.TextField(blank=True, default='content second', null=True)),
                ('content2_fi', models.TextField(blank=True, default='content second', null=True)),
                ('footer', models.TextField(blank=True, default='Regards,')),
                ('footer_en', models.TextField(blank=True, default='Regards,', null=True)),
                ('footer_fi', models.TextField(blank=True, default='Regards,', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='EmailContent',
        ),
        migrations.DeleteModel(
            name='PdfContents',
        ),
    ]
