# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0023_auto_20160717_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCopyContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name=b'Created on')),
                ('updated_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name=b'Updated on')),
                ('title', models.TextField(default='Title here', unique=True)),
                ('header', models.TextField(blank=True, default='Copy of mail requests')),
                ('content1', models.TextField(blank=True, default='content first')),
                ('content2', models.TextField(blank=True, default='content second')),
                ('footer', models.TextField(blank=True, default='Regards,')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='requestcontent',
            name='footer',
            field=models.TextField(blank=True, default='Footer here'),
        ),
        migrations.AlterField(
            model_name='requestcontent',
            name='footer_en',
            field=models.TextField(blank=True, default='Footer here', null=True),
        ),
        migrations.AlterField(
            model_name='requestcontent',
            name='footer_fi',
            field=models.TextField(blank=True, default='Footer here', null=True),
        ),
    ]
