# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0024_auto_20160723_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcopycontent',
            name='content1_en',
            field=models.TextField(blank=True, default='content first', null=True),
        ),
        migrations.AddField(
            model_name='requestcopycontent',
            name='content1_fi',
            field=models.TextField(blank=True, default='content first', null=True),
        ),
        migrations.AddField(
            model_name='requestcopycontent',
            name='content2_en',
            field=models.TextField(blank=True, default='content second', null=True),
        ),
        migrations.AddField(
            model_name='requestcopycontent',
            name='content2_fi',
            field=models.TextField(blank=True, default='content second', null=True),
        ),
        migrations.AddField(
            model_name='requestcopycontent',
            name='footer_en',
            field=models.TextField(blank=True, default='Regards,', null=True),
        ),
        migrations.AddField(
            model_name='requestcopycontent',
            name='footer_fi',
            field=models.TextField(blank=True, default='Regards,', null=True),
        ),
        migrations.AddField(
            model_name='requestcopycontent',
            name='title_en',
            field=models.TextField(default='Title', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='requestcopycontent',
            name='title_fi',
            field=models.TextField(default='Title', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='requestcopycontent',
            name='title',
            field=models.TextField(default='Title', unique=True),
        ),
    ]
