# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0025_auto_20160723_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcopycontent',
            name='title',
            field=models.TextField(default='Default', unique=True),
        ),
        migrations.AlterField(
            model_name='requestcopycontent',
            name='title_en',
            field=models.TextField(default='Default', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='requestcopycontent',
            name='title_fi',
            field=models.TextField(default='Default', null=True, unique=True),
        ),
    ]
