# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0029_auto_20160814_1816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaqContent',
        ),
    ]
