# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0030_delete_faqcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarequest',
            name='user_email_address',
            field=models.EmailField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestcontent',
            name='content3',
            field=models.TextField(blank=True, default='content third'),
        ),
    ]
