# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0031_auto_20160821_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcontent',
            name='content3_en',
            field=models.TextField(blank=True, default='content third', null=True),
        ),
        migrations.AddField(
            model_name='requestcontent',
            name='content3_fi',
            field=models.TextField(blank=True, default='content third', null=True),
        ),
    ]
