# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0032_auto_20160821_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationcontent',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AddField(
            model_name='datarequest',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
