# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0033_auto_20160830_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticationcontent',
            old_name='uuid',
            new_name='request_uuid',
        ),
        migrations.RenameField(
            model_name='datarequest',
            old_name='uuid',
            new_name='request_uuid',
        ),
    ]
