# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0034_auto_20160830_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenticationcontent',
            name='auth_field',
        ),
        migrations.RemoveField(
            model_name='authenticationcontent',
            name='data_request',
        ),
        migrations.RemoveField(
            model_name='datarequest',
            name='organization',
        ),
        migrations.DeleteModel(
            name='AuthenticationContent',
        ),
        migrations.DeleteModel(
            name='DataRequest',
        ),
    ]
