# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0035_auto_20160901_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcontent',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='requestcontent',
            name='content3_en',
        ),
        migrations.RemoveField(
            model_name='requestcontent',
            name='content3_fi',
        ),
    ]
