# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeedback',
            name='origin_url',
            field=models.TextField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
