# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(default='home', max_length=30, unique=True)),
                ('content', tinymce.models.HTMLField(blank=True, default='')),
            ],
        ),
    ]
