# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_extensions.db.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_fi',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='created_on',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 16, 16, 30, 58, 720991, tzinfo=utc), verbose_name=b'Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='updated_on',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 16, 16, 31, 5, 376684, tzinfo=utc), verbose_name=b'Updated on'),
            preserve_default=False,
        ),
    ]
