# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import home.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160716_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='admin_name',
            field=models.CharField(default='default', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=home.models.get_default_content),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, default=home.models.get_default_content, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content_fi',
            field=tinymce.models.HTMLField(blank=True, default=home.models.get_default_content, null=True),
        ),
    ]
