# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160718_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home page', 'verbose_name_plural': 'Home page'},
        ),
    ]
