# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160718_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=models.TextField(blank=True, default=home.models.get_default_content),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content_en',
            field=models.TextField(blank=True, default=home.models.get_default_content, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content_fi',
            field=models.TextField(blank=True, default=home.models.get_default_content, null=True),
        ),
    ]
