# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160718_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name=b'Created on')),
                ('updated_on', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name=b'Updated on')),
                ('title', models.CharField(default='', max_length=75)),
                ('priority', models.IntegerField(default=777)),
                ('content', tinymce.models.HTMLField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
