# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-14 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_faqcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcontent',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='faqcontent',
            name='content_fi',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='faqcontent',
            name='title_en',
            field=models.CharField(default='', max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='faqcontent',
            name='title_fi',
            field=models.CharField(default='', max_length=75, null=True),
        ),
    ]
